# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TCCalculator
                                 A QGIS plugin
 Time of Concentration Calculator using SCS/NRCS TR-55 methodology
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-01-08
        copyright            : (C) 2025 by Hydro Suite Development Team
        email                : support@hydrosuite.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TCCalculator class from file tc_calculator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tc_calculator import TCCalculator
    return TCCalculator(iface)